-- Vincula las compras G2 y sus liquidaciones G1 al centro real de acopio.
WHENEVER SQLERROR EXIT SQL.SQLCODE
-- Ejecutar una sola vez después de S07. No borra registros.
-- Si hay datos históricos y más de un centro, asigna sus centros manualmente
-- antes de ejecutar esta migración: no es seguro inferirlos por nombre o minero.
DECLARE
    v_centros NUMBER;
    v_historicos NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_centros FROM CENTROS_ACOPIO;
    SELECT (SELECT COUNT(*) FROM TRANSACCIONES_G2) + (SELECT COUNT(*) FROM LIQUIDACIONES_G1)
      INTO v_historicos FROM DUAL;
    IF v_centros > 1 AND v_historicos > 0 THEN
        RAISE_APPLICATION_ERROR(-20051,
            'Hay varios centros con historial: revisa la asignacion de compras y liquidaciones antes de migrar');
    END IF;
END;
/

ALTER TABLE TRANSACCIONES_G2 ADD (ID_CENTRO_ACOPIO NUMBER);
ALTER TABLE LIQUIDACIONES_G1 ADD (ID_CENTRO_ACOPIO NUMBER);

UPDATE TRANSACCIONES_G2 SET ID_CENTRO_ACOPIO = (SELECT MIN(ID_CENTRO_ACOPIO) FROM CENTROS_ACOPIO)
 WHERE ID_CENTRO_ACOPIO IS NULL;
UPDATE LIQUIDACIONES_G1 SET ID_CENTRO_ACOPIO = (SELECT MIN(ID_CENTRO_ACOPIO) FROM CENTROS_ACOPIO)
 WHERE ID_CENTRO_ACOPIO IS NULL;

ALTER TABLE TRANSACCIONES_G2 MODIFY (ID_CENTRO_ACOPIO NOT NULL);
ALTER TABLE LIQUIDACIONES_G1 MODIFY (ID_CENTRO_ACOPIO NOT NULL);

ALTER TABLE TRANSACCIONES_G2 ADD CONSTRAINT FK_G2_CENTRO
    FOREIGN KEY (ID_CENTRO_ACOPIO) REFERENCES CENTROS_ACOPIO(ID_CENTRO_ACOPIO);
ALTER TABLE LIQUIDACIONES_G1 ADD CONSTRAINT FK_G1_CENTRO
    FOREIGN KEY (ID_CENTRO_ACOPIO) REFERENCES CENTROS_ACOPIO(ID_CENTRO_ACOPIO);

CREATE INDEX IX_G2_CENTRO_STOCK ON TRANSACCIONES_G2 (ID_CENTRO_ACOPIO, ID_LIQUIDACION_G1, TIPO_ORO);
CREATE INDEX IX_G1_CENTRO ON LIQUIDACIONES_G1 (ID_CENTRO_ACOPIO);
COMMIT;
