-- Ejecutar en el esquema SITRA-ORO que contiene MAYORISTA_RECEPCIONES.
-- El peso fundido del acopiador entra como peso sin fundir del mayorista.
-- Permite dejar pendiente la nueva fundición. Conserva las filas y sus valores.
WHENEVER SQLERROR EXIT SQL.SQLCODE

DECLARE
    existentes NUMBER;
BEGIN
    SELECT COUNT(*) INTO existentes FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'MAYORISTA_RECEPCIONES' AND CONSTRAINT_NAME = 'CK_MAY_REC_ROJO_PESOS';
    IF existentes > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE MAYORISTA_RECEPCIONES DROP CONSTRAINT CK_MAY_REC_ROJO_PESOS';
    END IF;
    EXECUTE IMMEDIATE 'ALTER TABLE MAYORISTA_RECEPCIONES ADD CONSTRAINT CK_MAY_REC_ROJO_PESOS CHECK (
        (ROJO_PESO_SIN_FUNDIR_G IS NULL OR ROJO_PESO_SIN_FUNDIR_G >= 0)
        AND (ROJO_PESO_FUNDIDO_G IS NULL OR ROJO_PESO_FUNDIDO_G >= 0))';

    SELECT COUNT(*) INTO existentes FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'MAYORISTA_RECEPCIONES' AND CONSTRAINT_NAME = 'CK_MAY_REC_VERDE_PESOS';
    IF existentes > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE MAYORISTA_RECEPCIONES DROP CONSTRAINT CK_MAY_REC_VERDE_PESOS';
    END IF;
    EXECUTE IMMEDIATE 'ALTER TABLE MAYORISTA_RECEPCIONES ADD CONSTRAINT CK_MAY_REC_VERDE_PESOS CHECK (
        (VERDE_PESO_SIN_FUNDIR_G IS NULL OR VERDE_PESO_SIN_FUNDIR_G >= 0)
        AND (VERDE_PESO_FUNDIDO_G IS NULL OR VERDE_PESO_FUNDIDO_G >= 0))';

    SELECT COUNT(*) INTO existentes FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'MAYORISTA_RECEPCIONES' AND CONSTRAINT_NAME = 'CK_MAY_REC_CON_PESO';
    IF existentes > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE MAYORISTA_RECEPCIONES DROP CONSTRAINT CK_MAY_REC_CON_PESO';
    END IF;
    EXECUTE IMMEDIATE 'ALTER TABLE MAYORISTA_RECEPCIONES ADD CONSTRAINT CK_MAY_REC_CON_PESO CHECK (
        ROJO_PESO_SIN_FUNDIR_G IS NOT NULL OR VERDE_PESO_SIN_FUNDIR_G IS NOT NULL
        OR ROJO_PESO_FUNDIDO_G IS NOT NULL OR VERDE_PESO_FUNDIDO_G IS NOT NULL)';
END;
/
