CREATE TABLE LOTE_RECEPCIONES (
 ID_RECEPCION NUMBER PRIMARY KEY REFERENCES MAYORISTA_RECEPCIONES(ID_RECEPCION),
 ID_LOTE NUMBER NOT NULL REFERENCES LOTES_EXPORTACION(ID_LOTE) ON DELETE CASCADE,
 PESO_ROJO_G NUMBER(10,3) NOT NULL CHECK (PESO_ROJO_G >= 0),
 PESO_VERDE_G NUMBER(10,3) NOT NULL CHECK (PESO_VERDE_G >= 0)
);
