$salida = @"
SET LINESIZE 120 PAGESIZE 60 ECHO OFF FEEDBACK OFF
PROMPT ==============================================================
PROMPT === SISTEMA SITRA-ORO : ESTRUCTURA MAYORISTA_RECEPCIONES ===
PROMPT ==============================================================
DESC MAYORISTA_RECEPCIONES;
PROMPT
PROMPT === SITRA-ORO : REGISTROS DE DOBLE FUNDICION Y TOTALES ===
SELECT ID_RECEPCION, FECHA, ID_CENTRO_ACOPIO, ROJO_PESO_FUNDIDO_G AS ROJO_G, VERDE_PESO_FUNDIDO_G AS VERDE_G, TOTAL FROM MAYORISTA_RECEPCIONES WHERE ROWNUM <= 4;
EXIT;
"@ | & "C:\app\Paul\product\21c\dbhomeXE\bin\sqlplus.exe" -S BOMERP_APP/123456@localhost:1521/XEPDB1

Clear-Host
$salida
